{"uuid": "92fb3f96-8d70-4727-88b4-21a155780dee", "children": ["49cf89ae-5f5c-4027-b1c1-7d24184d25de"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=111.0.5563.147)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x0083DCE3]\n\t(No symbol) [0x007D39D1]\n\t(No symbol) [0x006E4DA8]\n\t(No symbol) [0x006CD0D3]\n\t(No symbol) [0x0072EA8B]\n\t(No symbol) [0x0073D093]\n\t(No symbol) [0x0072ACC6]\n\t(No symbol) [0x00706F68]\n\t(No symbol) [0x007080CD]\n\tGetHandleVerifier [0x00AB3832+2506274]\n\tGetHandleVerifier [0x00AE9794+2727300]\n\tGetHandleVerifier [0x00AEE36C+2746716]\n\tGetHandleVerifier [0x008E6690+617600]\n\t(No symbol) [0x007DC712]\n\t(No symbol) [0x007E1FF8]\n\t(No symbol) [0x007E20DB]\n\t(No symbol) [0x007EC63B]\n\tBaseThreadInitThunk [0x76487D69+25]\n\tRtlInitializeExceptionChain [0x779CB74B+107]\n\tRtlClearBits [0x779CB6CF+191]\n\n", "trace": "  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\testCases\\conftest.py\", line 11, in setup\n    request.cls.driver.maximize_window()\n  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 592, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1680189438473, "stop": 1680189442367}], "start": 1680189438473, "stop": 1680189442579}